version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - app-network

  signal_data_processor:
    build:
      context: ./signal_data_processor
      dockerfile: dockerfile.signal_data_processor  
    depends_on:
      - rabbitmq
    networks:
      - app-network

  real_data_processor:
    build:
      context: ./real_data_processor
      dockerfile: dockerfile.real_data_processor 
    depends_on:
      - rabbitmq
    networks:
      - app-network

  background_zz_processor:
    build:
      context: ./background_zz_processor
      dockerfile: dockerfile.background_zz_processor  
    depends_on:
      - rabbitmq
    networks:
      - app-network

  background_ztbar_processor:
    build:
      context: ./background_ztbar_processor
      dockerfile: dockerfile.background_ztbar_processor  
    depends_on:
      - rabbitmq
    networks:
      - app-network

  plotter:
    build:
      context: ./plotter
      dockerfile: dockerfile.plotter
    volumes:
      - ./output:/app/output  # Maps './output' on the host to '/app/output' in the container
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
