# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container to the directory of the script
WORKDIR /app

# Copy the requirements.txt file from the project root to the current directory
COPY ../requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory (background_Ztbar_processor) contents into the container at /app
COPY . .

# Set the Python script to run when the container launches
CMD ["python", "background_ztbar_processor.py"]
